// <auto-generated />
using System;
using HelpDesk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDesk.Infrastructure.Migrations
{
    [DbContext(typeof(HelpDeskDbContext))]
    [Migration("20260310033528_AddReopeningFields")]
    partial class AddReopeningFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HelpDesk.Domain.Ticket", b =>
                {
                    b.Property<int>("TicketDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TicketDbId"));

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("AssignedAgent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsOpenedByAgent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsOpenedByAgent");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ManagerId");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("TicketClosedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ClosedAt");

                    b.Property<Guid?>("TicketClosedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("ClosedById");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TicketId");

                    b.Property<DateTime?>("TicketReopenedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ReopenedAt");

                    b.HasKey("TicketDbId");

                    b.ToTable("Tickets", null, t =>
                        {
                            t.Property("Id")
                                .HasColumnName("Id1");
                        });
                });

            modelBuilder.Entity("HelpDesk.Domain.Ticket", b =>
                {
                    b.OwnsOne("HelpDesk.Domain.ValueObjects.SlaLimit", "CurrentSla", b1 =>
                        {
                            b1.Property<int>("TicketDbId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Deadline")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("SlaDeadline");

                            b1.HasKey("TicketDbId");

                            b1.ToTable("Tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketDbId");
                        });

                    b.OwnsMany("HelpDesk.Domain.ValueObjects.Message", "Messages", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("Text")
                                .HasColumnName("AuthorId");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("MessageContent");

                            b1.Property<DateTime>("SentAt")
                                .HasColumnType("datetime(6)");

                            b1.Property<int>("TicketId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("TicketId");

                            b1.ToTable("TicketMessages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("CurrentSla")
                        .IsRequired();

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
